### ISSUE TITLE
how to pass values from one command to another for window resizing?

### ISSUE THREAD

**Issue by thedewpoint** [theintern/intern-visual#15] opened 2019-04-11 12:51 UTC
I'm using the visual plugin with leadfoot in order to take some more dynamic screenshots. One thing I'd like to do is take full screen screenshots. In order to do this I have manually calculated the scrollheight and scrollwidth of the page and hardcoded it into the helpers.resizeWindow function before screenshotting. This has worked perfectly, but I'd like the values to be dynamic so I can reuse this configuration. I have tried calculating the scrollheight and scrollwidth dynamically using the execute command, but am struggling to pass the return values to the resize command correctly. Any advice is greatly appreciated.

Thank you

```javascript
registerSuite('homepage', {
	'homepage'() {
            return this.remote.get('myurl')
            .setWindowPosition(0,0)
            .maximizeWindow()
            .execute(() => [document.documentElement.scrollWidth, document.documentElement.scrollHeight])
            .then(([width, height]) => {
               return helpers.resizeWindow(width, height)
            })
			.takeScreenshot()
			.then(
				assertVisuals(this, {
                    missingBaseline: 'snapshot',
                    regenerateBaselines: true
				})
			);
	}
});
```

**Comment by jason0x43** [comment] 2019-04-11 13:56
Closing in favor of https://github.com/theintern/leadfoot/issues/171

**Closed as completed by jason0x43** 2019-04-11 13:56 UTC

**Comment by thedewpoint** [comment] 2019-04-11 15:43
I was actually able to solve this by doing 2 things. I removed the helper.resizeWindow and used the regular command.resizeWindow, and instead of embedding it within the callback function, i just placed it there without the curly braces and without a return statement. I'm unsure why this syntax works and the other did not.

```javascript
registerSuite('homepage', {
	'homepage'() {
            return this.remote.get('mypage')
            .setWindowPosition(0,0)
            .maximizeWindow()
            .execute(() => [document.documentElement.scrollWidth, document.documentElement.scrollHeight])
            .then(([width, height]) => this.remote.setWindowSize(width, height))
            .takeScreenshot()
			.then(
				assertVisuals(this, {
                    missingBaseline: 'snapshot',
                    regenerateBaselines: true
				})
			);
	}
});


```

**Comment by jason0x43** [comment] 2019-04-11 17:55
The issue is likely not the syntax, as these two are the same:

```js
.then(([width, height]) => this.remote.setWindowSize(width, height))
```
and
```
.then(([width, height]) => { return this.remote.setWindowSize(width, height)); })
```
The real difference is probably in how your `resizeWindow` helper is implemented vs `setWindowSize`.
